-- Game-state schema: the immutable run log plus small per-player aggregates.
--
-- Design (see repo memory.md): the client is authoritative during play and
-- submits one finished run per RPC; the server re-derives the score before
-- anything touches a leaderboard. Nothing user-facing ever scans `runs` —
-- stats, passport and boards are tiny rows maintained inside the same
-- transaction as the run insert. All writes go through security-definer
-- functions (next migration); tables grant SELECT only.

-- Guards the one-time replay of a guest's local progress after first login.
alter table public.profiles
  add column guest_import_done boolean not null default false;

-- ---------------------------------------------------------------- settings

-- Cloud copy of the client Settings object. JSONB so a new toggle never
-- needs a migration; updated_at arbitrates last-write-wins across devices.
create table public.player_settings (
  player_id uuid primary key references public.profiles (id) on delete cascade,
  settings jsonb not null check (pg_column_size(settings) <= 8192),
  updated_at timestamptz not null default now()
);

alter table public.player_settings enable row level security;

create policy "Members read their own settings"
  on public.player_settings for select
  to authenticated
  using ((select auth.uid()) = player_id);

create policy "Members insert their own settings"
  on public.player_settings for insert
  to authenticated
  with check ((select auth.uid()) = player_id);

create policy "Members update their own settings"
  on public.player_settings for update
  to authenticated
  using ((select auth.uid()) = player_id)
  with check ((select auth.uid()) = player_id);

grant select, insert, update on public.player_settings to authenticated;

create trigger player_settings_set_updated_at
  before update on public.player_settings
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------------- stats

-- Lifetime counters, bumped (never recomputed) by submit_run.
create table public.player_stats (
  player_id uuid primary key references public.profiles (id) on delete cascade,
  runs bigint not null default 0,
  correct bigint not null default 0,
  guesses bigint not null default 0,
  best_score bigint not null default 0,
  best_streak integer not null default 0,
  countries_discovered integer not null default 0,
  last_played_at timestamptz
);

alter table public.player_stats enable row level security;

create policy "Members read their own stats"
  on public.player_stats for select
  to authenticated
  using ((select auth.uid()) = player_id);

grant select on public.player_stats to authenticated;

-- -------------------------------------------------------------------- runs

-- Append-only event log and anti-cheat record. The id is generated by the
-- client so a retried submission is a no-op. Per-prompt detail rides in the
-- `guesses` JSONB (written once, never updated, always read whole).
create table public.runs (
  id uuid primary key,
  player_id uuid not null references public.profiles (id) on delete cascade,
  region text not null check (
    region in ('World', 'Africa', 'Asia', 'Europe', 'North America', 'South America', 'Oceania')
  ),
  round_length smallint not null check (round_length between 1 and 20),
  score bigint not null check (score >= 0),
  correct_count smallint not null check (correct_count >= 0),
  best_streak smallint not null check (best_streak >= 0),
  guesses jsonb not null check (pg_column_size(guesses) <= 16384),
  finished_at timestamptz not null default now()
);

create index runs_player_recent on public.runs (player_id, finished_at desc);

alter table public.runs enable row level security;

create policy "Members read their own runs"
  on public.runs for select
  to authenticated
  using ((select auth.uid()) = player_id);

grant select on public.runs to authenticated;

-- ---------------------------------------------------------------- passport

-- First-discovery ledger; insert-only, at most one row per country.
create table public.passport_stamps (
  player_id uuid not null references public.profiles (id) on delete cascade,
  country_iso text not null check (country_iso ~ '^[A-Z]{2}$'),
  first_discovered_at timestamptz not null default now(),
  primary key (player_id, country_iso)
);

alter table public.passport_stamps enable row level security;

create policy "Members read their own passport"
  on public.passport_stamps for select
  to authenticated
  using ((select auth.uid()) = player_id);

grant select on public.passport_stamps to authenticated;

-- -------------------------------------------------------- per-country skill

-- Cross-device signal for the adaptive prompt picker and future mastery
-- features. Bounded at one row per country per player.
create table public.player_country_stats (
  player_id uuid not null references public.profiles (id) on delete cascade,
  country_iso text not null check (country_iso ~ '^[A-Z]{2}$'),
  hits integer not null default 0,
  misses integer not null default 0,
  hints_used integer not null default 0,
  last_seen_at timestamptz not null default now(),
  primary key (player_id, country_iso)
);

alter table public.player_country_stats enable row level security;

create policy "Members read their own country stats"
  on public.player_country_stats for select
  to authenticated
  using ((select auth.uid()) = player_id);

grant select on public.player_country_stats to authenticated;

-- ------------------------------------------------------------- leaderboards

-- One row per player per board, best score only. The board key encodes
-- period + region ('alltime:World', 'weekly:2026-W30:Europe') so a single
-- table serves every board, reads are one index range scan, and expired
-- boards prune by key. Reads go through get_leaderboard (security definer)
-- so display names can be joined without opening profiles to the world;
-- no direct grants on the table itself.
create table public.leaderboard_entries (
  board text not null check (board ~ '^(alltime|weekly:[0-9]{4}-W[0-9]{2}):[A-Za-z ]+$'),
  player_id uuid not null references public.profiles (id) on delete cascade,
  score bigint not null check (score > 0),
  correct_count smallint not null,
  round_length smallint not null,
  achieved_at timestamptz not null default now(),
  primary key (board, player_id)
);

create index leaderboard_top on public.leaderboard_entries (board, score desc);

alter table public.leaderboard_entries enable row level security;
